id: IECB9690E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:29:00+00:00'
last_modified: '2022-06-08T17:21:05.927504+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16555
  title: བོན་གྱི་ལོ་རྒྱུས་ཡིག་ཆ་ཕྱོགས་སྒྲིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3820':
      image_group_id: I2PD18269
      title: ''
      total_pages: 518
      order: 1
      base_file: 3820.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
